### ISSUE TITLE
Event attribute values are not returned correctly when calling for a specific event ID.

### ISSUE THREAD

**Issue by i3iorn** [aiqueneldar/participantcaller#13] opened 2019-06-03 21:04 UTC
Event attribute values are not returned correctly when calling for a specific event ID.

The call:
https://2m9ajz98wd.execute-api.eu-west-1.amazonaws.com/Test/api/v1/event?eventid=1
returns these event attributes:
"eventattributes": [[1, "mi. Duis risus", null], [59, "auctor ullamcorper, nisl", null]]
it should be:
"eventattributes": [[1, "mi. Duis risus", 625], [59, "auctor ullamcorper, nisl", 927]]

_Originally posted by @i3iorn in https://github.com/aiqueneldar/participantcaller/issues/5#issuecomment-498421352_

**Comment by aiqueneldar** [comment] 2019-06-27 01:50
I have found the confusion, or so I think.
When it comes to attributes, what is returned is [`attributeID`, `attributeName`, `parentAttribute`] not the value of the attribute itself. So technically it is not a bugg, code returns expected values.
It is rather a question of what values should be returned, and how. 
I would agree that the attribute value should be returned. And perhaps return in the form of a MAP so it is easier to distinguish what value is what.

**Comment by aiqueneldar** [comment] 2019-06-27 02:27
Now the API returns a much easier to read and understand result. Also, it includes the values of the attributes. Will close this.

**Closed as completed by aiqueneldar** 2019-06-27 02:27 UTC
Labels: enhancement, invalid
